### ISSUE TITLE
et_replay encounters an issue when launched

### ISSUE THREAD

**Issue by rafsalas19** [facebookresearch/param#179]
## Describe the Bug
Trace:
```
$ et_replay --input benchmark_result_3980675_1725663040_et.json --warmup-iter 10 --iter 50 --compute --profile-replay
[2024-09-09 21:37:15,204] et_replay.py:175 [INFO]: FB internals not present
#Operators to execute:  4
Tensor count with same identifier but different shapes:0, total tensor: 2
Tensor allocation time: 0.017042 ms
Start execution: 
[2024-09-09 21:37:19,737] utils.py:30 [WARNING]: Chrome profile trace written to /tmp/tmp_20240909_363a978_1218607.json
Traceback (most recent call last):
  File "/home/azureuser/anaconda3/envs/param/bin/et_replay", line 8, in <module>
    sys.exit(main())
  File "/home/azureuser/anaconda3/envs/param/lib/python3.8/site-packages/et_replay/tools/et_replay.py", line 1851, in main
    replay_manager.benchTime()
  File "/home/azureuser/anaconda3/envs/param/lib/python3.8/site-packages/et_replay/tools/et_replay.py", line 1625, in benchTime
    run_iter(iter)
  File "/home/azureuser/anaconda3/envs/param/lib/python3.8/site-packages/et_replay/tools/et_replay.py", line 1555, in run_iter
    / ((time.time_ns() - start_ns) / 1000000000)
UnboundLocalError: local variable 'start_ns' referenced before assignment
```

## Steps to Reproduce
`et_replay --input benchmark_result_3980675_1725663040_et.json --warmup-iter 10 --iter 50 --compute --profile-replay`

**Comment by shengfukevin** [comment]
Thanks for reporting this issue. et_replay just got updated last Friday. Can you try the latest version? If you still see the error, please let us know.
