### ISSUE TITLE
How do I generate traces for replay?

### ISSUE THREAD

**Issue by ChenYuHo** [facebookresearch/param#23]
Hi,
I wonder what is the expected trace format for `commsTraceReplay.py` and how to generate them?
I tried with traces captured with the latest (PyTorch at tag v1.9.0-rc2 commit d417a094f398f1c4efd7f818b14b8471a597fbcc) [PyTorch profiler](https://pytorch.org/docs/stable/profiler.html) following the doc:
```python
def trace_handler(prof):
        prof.export_chrome_trace(f"rank{args.rank}.json")

with torch.profiler.profile(activities=[torch.profiler.ProfilerActivity.CPU,torch.profiler.ProfilerActivity.CUDA],
    schedule=torch.profiler.schedule(wait=1,warmup=10,active=2),
    on_trace_ready=trace_handler) as p:
    for _ in range(args.iterations):
        my_training_code_using_DistributedDataParallel()
        p.step()
```

but got errors with those traces:
```bash
mpirun -np 2 -H ${HOST1_IP},${HOST2_IP} python commsTraceReplay.py --master-ip $HOST1_IP --backend nccl --device cuda --trace-path /path/to/rankR.json

Traceback (most recent call last):
  File "/home/param/train/comms/pt/commsTraceReplay.py", line 708, in <module>
    main()
  File "/home/param/train/comms/pt/commsTraceReplay.py", line 704, in main
    traceBench.runBench(comms_world_info, commsParams)
  File "/home/param/train/comms/pt/commsTraceReplay.py", line 562, in runBench
    self.initTraceStat()
  File "/home/param/train/comms/pt/commsTraceReplay.py", line 274, in initTraceStat
    for curComm in self.comms_trace[:self.max_msg_cnt]:
TypeError: unhashable type: 'slice'
```

Thank you!

**Comment by louisfeng** [comment]
This issue has been stale for too long. Will close for now. If issue still persist, please let us know. I know there are work in progress on updating the comms replay trace.
