### ISSUE TITLE
"Unrecognised argument(s): force" for comms/pt/comms_utils.py 

### ISSUE THREAD

**Issue by amathews-amd** [facebookresearch/param#65]
https://github.com/facebookresearch/param/blame/main/train/comms/pt/comms_utils.py#L1734

```
Traceback (most recent call last):
  File "./comms.py", line 1405, in <module>
    main()
  File "./comms.py", line 1362, in main
    collBenchObj.checkArgs(args)
  File "./comms.py", line 239, in checkArgs
    super().checkArgs(args)
  File "/myworkspace/param/train/comms/pt/comms_utils.py", line 1734, in checkArgs
    force=True,
  File "/opt/conda/lib/python3.7/logging/__init__.py", line 1919, in basicConfig
    raise ValueError('Unrecognised argument(s): %s' % keys)
ValueError: Unrecognised argument(s): force
```

**Comment by kingchc** [comment]
@amathews-amd - thanks for reporting this issue, this argument  option is only supported for python3.8+. If possible, please use python 3.8 or later to unblock your work for now, we will fix it soon.
