### ISSUE TITLE
commsTraceReplay failing due to missing import

### ISSUE THREAD

**Issue by harisj-xlnx** [facebookresearch/param#76]
I used torch.profiler.profile to collect some traces and replay them using commsTraceReplay. I encountered the following error:

```
Traceback (most recent call last):
  File "./commsTraceReplay.py", line 1247, in readTrace
    import commsTraceParser
ModuleNotFoundError: No module named 'commsTraceParser'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./commsTraceReplay.py", line 1329, in <module>
    main()
  File "./commsTraceReplay.py", line 1325, in main
    traceBench.runBench(commsParams)
  File "./commsTraceReplay.py", line 1000, in runBench
    self.readTrace(remotePath=self.trace_file, rank=global_rank)
  File "./commsTraceReplay.py", line 1250, in readTrace
    self.comms_trace = extractCommsInfo(self.comms_trace)
  File "./commsTraceReplay.py", line 1266, in extractCommsInfo
    newComm.comms = paramToCommName(curComm["comms"].lower())
TypeError: string indices must be integers
Traceback (most recent call last):
  File "./commsTraceReplay.py", line 1247, in readTrace
    import commsTraceParser
ModuleNotFoundError: No module named 'commsTraceParser'
```

Looks like there is no module named commsTraceParser in the entire repo.

**Comment by louisfeng** [comment]
cc: @shengbao-zheng

**Comment by louisfeng** [comment]
Thanks @harisj-xlnx, we are aware of the issue and looking into it.

**Comment by louisfeng** [comment]
Looks like it's been fixed.
